#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 callback_url" >&2
  exit 1
fi

callback_url="$*"

parse_lines() {
  while read -r line
  do
    echo -n $line | grep -sq "Waiting for .* callbacks..." && /usr/share/smartwink/apronpair_callback "$callback_url" "ready"
    echo -n $line | sed -u -n 's/^[[:space:]]*Status:[[:space:]]*//p' | xargs -r -n 1 /usr/share/smartwink/apronpair_callback "$callback_url"
  done
}

/usr/local/bin/socat -u EXEC:"aprontest -a -r lutron",stderr,pty,ctty,end-close - | parse_lines

wait

