#!/bin/sh

usage() {
  echo "Usage: $0 <lutron output file>" >&2
  exit 1
}

parse_lines() {
  # This has to work with unbuffered output. So grep and cut are out, but
  # sed and awk work.
  # Note: It looks like Lutron IDs can be four bytes long! But apron only looks at 3, so we'll only look at 3.
  sed -u -n '/^Device -->.*(00)[^(]*(81)/p' $1 | sed -u 's/[^)]*(\([0-9a-f]*\))[^(]*/\1 /g' | sed -u 's/^.*81 00 //' | awk '{ printf "%s %s %s ", $1, $2, $3; if ($5=="00") { print $6 } else { print $5 }; fflush(); }' | sed -u -n '/^.. .. .. ..$/p' | xargs -r -n 4 button-pressed
}

[ $# -eq 0 ] && usage

parse_lines $1
