#!/bin/sh

usage() {
  echo "Usage: $0 <lutron output file>" >&2
  exit 1
}

parse_lines() {
  # This has to work with unbuffered output. So grep and cut are out, but
  # sed and awk work.
  sed -u -n '/^Device -->.*(00)[^(]*(81)/p' $1 | sed -u 's/[^)]*(\([0-9a-f]*\))[^(]*/\1 /g' | awk '{ print $8, $9, $10, $12; fflush(); }' | sed -u -n '/^.. .. .. ..$/p' | xargs -r -n 4 button-pressed
}

[ $# -eq 0 ] && usage

parse_lines $1
