
 *  __description__ device type for __app__.
 *
 *  Author: __author__ (__author_email__)
 *
 *  This file is automatically generated from a template. Do not modify directly.
 *  Please refer to __source_url__ for the source code.